#! /usr/bin/python3

addon_desc = (
("tkit",
"tkit adds several ways of selecting neighboring mesh elements in edge mode."),
("shiftsemi",
"shiftsemi lets you press shift+semicolon in the viewport to rename the selection. Works on multiple objects. Renames data (also bones)."),
("pcloud",
"With a mesh object selected, rip the locations of the active particle system into a new mesh."))

import xml.dom.minidom as xml

def xml_docattr(d,k):
    try:
        return object.__getattribute__(d,k)
    except AttributeError:
        return d.createElement(k)

xml.Document.__getattribute__ = xml_docattr

def xml_elem_setattrs(e,**a):
    for k,v in a.items():
        e.setAttribute(k,str(v))
    return e

xml.Element.attrs = xml_elem_setattrs

xml.Element.__iadd__ = lambda s,o:[s.appendChild(o),s][-1]
xml.Element.txt = lambda s,t:[s.appendChild(s.ownerDocument.createTextNode(t)),s][-1]
xml.Element.__str__ = lambda s:s.toprettyxml().strip()

_ = xml.Document()
html = _.html
head = _.head
body = _.body
html += head
html += body
head += _.title.txt("dustractor.github.io")
head += _.meta.attrs(name="content",type="text/html; charset=utf-8")
head += _.link.attrs(href="style/screen.css",type="text/css",rel="stylesheet")

main = _.main
body += main

header = _.header
main += header
header += _.h1.txt("Welcome to dustractor.github.io")

addon_article = _.article
main += addon_article
addon_article += _.h2.txt("Blender Addons")
ul = _.ul
addon_article += ul

for name,desc in addon_desc:
    li = _.li
    a = _.a.attrs(href="/"+name).txt(name)
    li += a
    p = _.p.txt(desc)
    li += p
    ul += li

footer = _.footer
main += footer
footer += _.h3.txt("࿇2016")
main += footer

print("<!DOCTYPE html>" + "\n" + str(html))

